[General]
# Rewritten by `sddm-theme refresh` from ~/.config/quickshell/colors.json and the current wallpaper.
background=background.png
font=RobotoMono Nerd Font
clock24h=false
radius=14
primary=#f6bc70
primaryFg=#462b00
primaryContainer=#643f00
primaryContainerFg=#ffddb6
surfaceLow=#211b13
surfaceHigh=#302921
surfaceHighest=#3b342b
text=#ede0d4
textDim=#d3c4b4
error=#ffb4ab
outline=#9c8e80
outlineVariant=#4f4539
