#!/bin/bash
#
# This script manages the desktop wallpaper, allowing you to choose from a thumbnail grid
# of images found in the wallpapers directory (default to "$HOME/Pictures/Wallpapers").
#
# Dependencies: rofi, swww, pywal, mako, waybar
# Optional: feh

SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit; pwd -P )"

ROFI_CMD="${ROFI_CMD:-rofi -dmenu -i}"
ROFI_CONFIG_DIR="${ROFI_CONFIG_DIR:-$SCRIPT_PATH/config}"
WALLPAPERS_DIR="${WALLPAPERS_DIR:-$HOME/Pictures/Wallpapers}"  # Updated to new directory
WALLPAPER_CACHE="$ROFI_CONFIG_DIR/wallpapers"
GRID_ROWS=${GRID_ROWS:-2}   # Number of rows
GRID_COLS=${GRID_COLS:-6}   # Number of columns

# Function to build rofi theme string
build_theme() {
    rows=$1
    cols=$2
    icon_size=6  # Size of the icon
    echo "element {orientation: vertical;} element-text {horizontal-align: 0.5;} element-icon {size: ${icon_size}.0000em;} listview {lines: ${rows}; columns: ${cols};}"
}

# Find images and format for rofi
images=$(find "$WALLPAPERS_DIR" -type f -maxdepth 1 -printf "%T@ %f\x00icon\x1f$WALLPAPERS_DIR/%f\n" | sort -rn | cut -d' ' -f2-)

# Show rofi menu and get user's choice
choice=$(echo -en "Random Choice\n$images" | $ROFI_CMD -show-icons -theme-str "$(build_theme $GRID_ROWS $GRID_COLS)" -p "Wallpaper")

if [ -z "$choice" ]; then
    echo "No wallpaper selected. Exiting."
    exit 1
fi

# Determine the selected wallpaper
if [ "$choice" == "Random Choice" ]; then
    selected_wallpaper=$(find "$WALLPAPERS_DIR" -type f | shuf -n 1)
else
    selected_wallpaper="$WALLPAPERS_DIR/$choice"
fi

# Input wallpaper
input_image="$selected_wallpaper"

# Paths for the normal and blurred wallpapers
normal_image="/home/idea/.cache/normal-wallpaper.png"
output_image="/home/idea/.cache/blurred-wallpaper.png"

# Copy the input wallpaper to .cache/normal-wallpaper.png
echo "Copying the input wallpaper to $normal_image..."
cp "$input_image" "$normal_image"

# Apply the colors from the provided image
echo "Applying wallpaper: $input_image"
wal -i "$input_image"

# Restart Waybar
echo "Restarting Waybar..."
killall waybar
nohup waybar </dev/null >/dev/null 2>&1 & disown

# Resize the image to 1280x720
echo "Resizing the image to 1280x720..."
magick "$input_image" -resize 1280x720 "$output_image"

# Blur the wallpaper
echo "Blurring wallpaper..."
magick "$output_image" -blur 0x8 "$output_image"

# Set the blurred wallpaper with wpgtk
#echo "Setting wallpaper with wpgtk..."
#wpg -s /home/idea/.cache/normal-wallpaper.png -n --noterminal

# Update Firefox theme with pywalfox
echo "Updating Firefox theme with pywalfox..."
pywalfox update

# swwnc reload
swaync-client -C
swaync-client -rs
swaync-client -R

# Notify the user
notify-send "Wallpaper Set" "The selected wallpaper has been applied successfully. Enjoy your new look!"

echo "Done! Original wallpaper saved as $normal_image, blurred wallpaper saved as $output_image."

