-- Hyprland config (Lua). Refer to https://wiki.hypr.land/Configuring/Start/
-- Palette: colors.lua (generated by matugen), falling back to colors-default.lua.

local home = os.getenv("HOME")
local hypr = home .. "/.config/hypr"

-- dofile instead of require so a reload always sees the newest generated palette
local function load_colors()
    for _, file in ipairs({ "colors.lua", "colors-default.lua" }) do
        local ok, palette = pcall(dofile, hypr .. "/" .. file)
        if ok and type(palette) == "table" then
            return palette
        end
    end
    return {}
end
local c = load_colors()


------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "alacritty"
local fileManager = "thunar"
local menu        = "qs ipc call launcher toggle" -- Quickshell app launcher


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd(hypr .. "/scripts/seed-colors.sh") -- generated colors missing? create a starter set
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")  -- clipboard history (Super+V)
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("qs") -- Quickshell: bar, launcher, notifications, OSD, menus (~/.config/quickshell)
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(hypr .. "/scripts/gtk-settings.sh")
    hl.exec_cmd("kdeconnect-indicator") -- starts kdeconnectd too; harmless if not installed
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 12,

        border_size = 2,

        col = {
            active_border   = { colors = { c.primary or "rgba(ffb4a9ff)" }, angle = 45 },
            inactive_border = c.outline_variant or "rgba(534341ff)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding         = 12,
        active_opacity   = 0.92,
        inactive_opacity = 0.82,
        fullscreen_opacity = 1,

        shadow = {
            enabled      = true,
            range        = 12,
            render_power = 3,
            color        = "rgba(00000066)",
        },

        blur = {
            enabled           = true,
            size              = 8,
            passes            = 3,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = true,
            vibrancy_darkness = 0.0,
            popups            = false,
            vibrancy          = 0.17,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}    } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}  } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- "Smart gaps" / "No gaps when only": see the example config in /usr/share/hypr/hyprland.lua

hl.config({
    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0, -- awww draws the wallpaper; no mascot flash at startup
        disable_hyprland_logo   = true,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll       = false,
            disable_while_typing = false,
        },
    },
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

hl.bind(mainMod .. " + T",           hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Q",           hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + M",   hl.dsp.exit())
hl.bind(mainMod .. " + Escape",      hl.dsp.exec_cmd("qs ipc call power toggle"))
hl.bind(mainMod .. " + N",           hl.dsp.exec_cmd("qs ipc call controlcenter toggle"))
hl.bind(mainMod .. " + G",           hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",           hl.dsp.exec_cmd("qs ipc call clipboard toggle"))  -- clipboard history
hl.bind(mainMod .. " + Tab",         hl.dsp.exec_cmd("qs ipc call overview toggle"))  -- workspace overview
hl.bind(mainMod .. " + period",      hl.dsp.exec_cmd("qs ipc call emoji toggle"))  -- emoji picker
hl.bind(mainMod .. " + SHIFT + V",   hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D",           hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + Z",           hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + B",           hl.dsp.exec_cmd("qs ipc call config bar toggle")) -- hide / bring back the bar
hl.bind(mainMod .. " + I",           hl.dsp.exec_cmd("qs ipc call settings toggle")) -- Settings from anywhere
hl.bind(mainMod .. " + W",           hl.dsp.exec_cmd("qs ipc call theme toggle"))
hl.bind(mainMod .. " + P",           hl.dsp.window.pseudo())          -- dwindle
hl.bind(mainMod .. " + J",           hl.dsp.layout("togglesplit"))    -- dwindle
hl.bind(mainMod .. " + F",           hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F",   hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })) -- maximize, keep bar

-- Screenshots: the Quickshell tool (toolbar, delay, preview card). If Quickshell
-- isn't running, `qs ipc` fails and the plain script takes over.
local shot = hypr .. "/scripts/screenshot.sh"
local function capture(mode, flag)
    return hl.dsp.exec_cmd("qs ipc call screenshot " .. mode .. " || " .. shot .. " " .. flag)
end
hl.bind("Print",                     capture("area", "--area"))
hl.bind("SHIFT + Print",             capture("screen", "--now"))
hl.bind("ALT + Print",               capture("window", "--win"))
hl.bind(mainMod .. " + K",           capture("toggle", "--area")) -- toolbar: mode, delay, copy/save
hl.bind(mainMod .. " + SHIFT + K",   capture("screen", "--now"))

-- Alt+Tab window switcher (Quickshell); releasing Alt picks the window
hl.bind("ALT + Tab",                 hl.dsp.exec_cmd("qs ipc call switcher next"))
hl.bind("ALT + SHIFT + Tab",         hl.dsp.exec_cmd("qs ipc call switcher prev"))
hl.bind("ALT + Alt_L",               hl.dsp.exec_cmd("qs ipc call switcher commit"), { release = true, transparent = true })

-- Move focus with mainMod + arrow keys
-- Move windows with mainMod + SHIFT + arrow keys
for key, dir in pairs({ left = "left", right = "right", up = "up", down = "down" }) do
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ direction = dir }))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ direction = dir }))
end

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Scratchpad
hl.bind(mainMod .. " + S",           hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S",   hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down",  hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",    hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272",   hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273",   hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness (the OSD is Quickshell)
local keys = { locked = true, repeating = true }
hl.bind("XF86AudioRaiseVolume",      hl.dsp.exec_cmd("qs ipc call osd volumeUp"),       keys)
hl.bind("XF86AudioLowerVolume",      hl.dsp.exec_cmd("qs ipc call osd volumeDown"),     keys)
hl.bind("XF86AudioMute",             hl.dsp.exec_cmd("qs ipc call osd volumeMute"),     keys)
hl.bind("XF86AudioMicMute",          hl.dsp.exec_cmd("qs ipc call osd micMute"),        keys)
hl.bind("XF86MonBrightnessUp",       hl.dsp.exec_cmd("qs ipc call osd brightnessUp"),   keys)
hl.bind("XF86MonBrightnessDown",     hl.dsp.exec_cmd("qs ipc call osd brightnessDown"), keys)

-- Requires playerctl
hl.bind("XF86AudioNext",             hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause",            hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",             hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",             hl.dsp.exec_cmd("playerctl previous"),   { locked = true })


---------------------------
---- LAYER RULES (blur) ----
---------------------------

-- Quickshell windows blur what is behind them wherever their fill is translucent.
-- Full-screen overlays have a dim scrim, so they ignore low alpha (the scrim stays unblurred).
hl.layer_rule({
    name  = "qs-blur-bars",
    match = { namespace = "^(qs-bar|qs-dock|quickshell-(osd|notifications|screenshot-preview))$" },
    blur         = true,
    ignore_alpha = 0.2,
})
-- Power menu and goodbye screen: blur the whole screen, scrim included
-- Launcher: blur only behind the (translucent) card; the light dim scrim stays sharp
hl.layer_rule({
    name  = "qs-blur-launcher",
    match = { namespace = "^qs-launcher$" },
    blur         = true,
    ignore_alpha = 0.45,
})
hl.layer_rule({
    name  = "qs-blur-powermenu",
    match = { namespace = "^qs-powermenu$" },
    blur         = true,
    ignore_alpha = 0.01,
})
hl.layer_rule({
    name  = "qs-blur-panels",
    match = { namespace = "^(qs-panel)$" },
    blur         = true,
    ignore_alpha = 0.25,
})


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/

hl.window_rule({
    -- Ignore maximize requests from all apps
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
    -- Video and browsers stay fully opaque
    name  = "opaque-media",
    match = { class = "^(mpv|firefox|zen|imv)$" },

    opacity = "1.0 override 1.0 override",
})

hl.window_rule({
    -- Small tools float
    name  = "float-tools",
    match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol|nm-connection-editor|nwg-look|qt6ct|qt5ct)$" },

    float = true,
})

hl.window_rule({
    -- File pickers float
    name  = "float-file-dialogs",
    match = { title = "^(Open File|Save File|Open Folder)(.*)$" },

    float = true,
})
